<?php
// Harisfazillah Jamel v 3.1 27 Dec 2025
// XML Sitemap for Search Engines
// Generated by Google Gemini

require_once __DIR__ . '/vendor/autoload.php';

header("Content-Type: text/xml; charset=utf-8");

require_once 'includes/sitemap_generator.php';

// Determine Base URL
$protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http";
$host = $_SERVER['HTTP_HOST'];
$path = dirname($_SERVER['PHP_SELF']);
// Ensure path ends with slash if it's just root, but dirname often returns \ or / excluding trailing
// Safe Base URL construction:
$baseUrl = "$protocol://$host" . rtrim($path, '/\\');

echo '<?xml version="1.0" encoding="UTF-8"?>';
?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<?php
$pages = get_site_pages();
foreach ($pages as $page): 
?>
    <url>
        <loc><?= $baseUrl . '/' . $page['file'] ?></loc>
        <lastmod><?= $page['lastmod'] ?></lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
<?php endforeach; ?>
</urlset>
