---
- name: Ensure Target Directory Exists
  ansible.builtin.file:
    path: "{{ cms_deploy_path }}"
    state: directory
    owner: 1501
    group: 1501
    mode: '0700'

- name: Clone CmsForNerd Official Repository
  ansible.builtin.git:
    repo: 'https://github.com/CMSForNerd/CmsForNerd.git'
    dest: "{{ cms_deploy_path }}"
    version: master
    force: true
    depth: 1
  become: true
  become_user: cmsfornerd

- name: Set secure file ownership
  ansible.builtin.file:
    path: "{{ cms_deploy_path }}"
    owner: 1501
    group: 1501
    recurse: true

- name: Install dependencies via Composer (inside a temporary container)
  containers.podman.podman_container:
    name: cmsfornerd-composer
    image: docker.io/library/composer:2.8
    state: started
    user: "1501:1501"
    volumes:
      - "{{ cms_deploy_path }}:/app:Z"
    command: install --ignore-platform-reqs --no-dev --optimize-autoloader
    detach: false
    rm: true
    security_opt:
      - no-new-privileges
  become: true
  become_user: cmsfornerd
