---
- name: Ensure Target Directory Exists
  ansible.builtin.file:
    path: "{{ cms_deploy_path }}"
    state: directory
    owner: "{{ podman_cms_uid }}"
    group: "{{ podman_cms_gid }}"
    mode: '0700'

- name: Clone CmsForNerd Official Repository
  ansible.builtin.git:
    repo: 'https://github.com/CMSForNerd/CmsForNerd.git'
    dest: "{{ cms_deploy_path }}"
    version: master
    force: true
    depth: 1
  become: true
  become_user: "{{ podman_cms_user }}"

- name: Set secure file ownership
  ansible.builtin.file:
    path: "{{ cms_deploy_path }}"
    owner: "{{ podman_cms_uid }}"
    group: "{{ podman_cms_gid }}"
    recurse: true

- name: Install dependencies via Composer (inside a temporary container)
  containers.podman.podman_container:
    name: cmsfornerd-composer
    image: docker.io/library/composer:2.8
    state: started
    user: "{{ podman_cms_uid }}:{{ podman_cms_gid }}"
    volumes:
      - "{{ cms_deploy_path }}:/app:Z"
    command: install --ignore-platform-reqs --no-dev --optimize-autoloader
    detach: false
    rm: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - all
  become: true
  become_user: "{{ podman_cms_user }}"
