    <meta name="Robots" content="index,follow" />
    <link href="http://cmsfornerd.harisfazillah.info/favicon.ico" type="image/x-icon" rel="shortcut icon" />
    <link href="http://cmsfornerd.harisfazillah.info/favicon.ico" type="image/x-icon" rel="icon" />
    <link rel="shortcut icon" href="http://cmsfornerd.harisfazillah.info/favicon.ico" />
    <link rel="alternate" type="application/rss+xml" title="CmsForNerd SiteMap Feed" href="http://cmsfornerd.harisfazillah.info/rss.xml" />
    <meta http-equiv="PICS-Label" content='(PICS-1.1 "http://www.classify.org/safesurf/" L gen true for "http://cmsfornerd.harisfazillah.info/" r (SS~~000 1))' />
    <link rel="meta" href="http://cmsfornerd.harisfazillah.info/labels.rdf" type="application/rdf+xml" title="ICRA labels" />

    <link rel="alternate" type="application/rss+xml" title="CmsForNerd ROR Sitemap" href="http://cmsfornerd.harisfazillah.info/ror.xml" />
    <meta name="Security" content="Public" />
    <meta name="googlebot" content="archive" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="EN" />