<h3 style="text-align: justify;">Introduction</h3>
<div style="text-align: justify;"><a
 href="http://cmsfornerd.harisfazillah.info/"><span
 style="font-weight: bold;">CmsForNerd</span></a>
is really for nerd. You need to know basic HTML, CSS and PHP to
maintain it because it is not like any other content Management
Software or CMS. We build <span style="font-weight: bold;">CmsForNerd</span>
because we want to learn about HTML and how to code in PHP.<br />
<br />
<span style="font-weight: bold;">CmsForNerd</span>
is for a small website, with static contents that not always need to be
change. <span style="font-weight: bold;">CmsForNerd</span>
is not using any database. We want a CMS that it is simple, easy to
backup and recovery because we don't want to be worried about any lost
of data in database due to hardware failure.<br />
<br />
We also build <span style="font-weight: bold;">CmsForNerd</span>
so it is search engine friendly to Google and Yahoo. You can used <a
 href="http://users.skynet.be/mgueury/mozilla/" target="_blank">HTML
Validator</a> add-on for Mozilla Firefox &nbsp;to validate
yout HTML page.<br />
</div>
<h3 style="text-align: justify;">Installation</h3>
<div style="text-align: justify;">Download the zip or tar
ball and expand it inside the public directory of your web server. The
web server need to support PHP.<br />
</div>
<h3 style="text-align: justify;">Configuration</h3>
<div style="text-align: justify;">To create a page in <span
 style="font-weight: bold;">CmsForNerd</span>, it's
used two files, one file need to be located at top level of webite with
extension PHP (dot PHP <span style="font-weight: bold;">.php</span>).
Another file located in contents directory (folder) with extension INC
(dot INC .inc). Both must begin with the same name and need to follow
this specific name format. For example the PHP file with name <span
 style="font-weight: bold;">test.php</span> should has
file name <span style="font-weight: bold;">test-body.inc</span>
in contents directory.<br />
<br />
The template files of <a
 href="http://cmsfornerd.harisfazillah.info/"><span
 style="font-weight: bold;">CmsForNerd</span></a>
located in top level of the website and <span
 style="font-weight: bold;">contents</span> directory
(folder). You can use <a target="_blank"
 href="http://www.nvu.com/">NVU</a> to code your <span
 style="font-weight: bold;">HTML</span>. Just copy the
content between <span style="font-weight: bold;">BODY TAG</span>
of your HTML source and put in your INC file. Your INC file should be
named as per the PHP file at the top level of your website.<br />
<br />
For example if your page name is <span style="font-weight: bold;">search.php</span>
then the file in the <span style="font-weight: bold;">contents</span>
directory should be <span style="font-weight: bold;">search-body.inc</span>.
<br />
<br />
Don't forget to copy at the top level of your website the file <span
 style="font-weight: bold;">template.php</span> into
the&nbsp; name as per your file inside contents directory. Your
need to edit the PHP file to customize the information HTML TAG as per
your page content.<br />
<br />
For Web GUI interface, <a href="http://www.net2ftp.org/"
 target="_blank">net2ftp</a> a web based FTP client is
recommeded to be use.<br />
<br />
</div>
