<div align="left" class="buttonscontainer"> 

<div align="left" class="buttons"> 

<a href="index.php">Home</a>
<a href="https://www.linuxmalaysia.com">CmsForNerd</a>
<a href="https://github.com/LinuxMalaysia/CMSForNerd-Project/archive/refs/heads/master.zip">Download</a>
<a href="template.php">CmsForNerd Template</a>
<a href="sitemap.php">CmsForNerd Sitemap</a>
<a href="installation.php">CmsForNerd Installation</a>
<a href="https://www.linuxmalaysia.com">CmsForNerd Blog</a>

</div>

</div>

<br>

<h3>E-Mail</h3>
 
<br>			

<h3>Joint Us</h3>

<div style="text-align: center; font-family: Verdana;">

<table style="background-color: #fff; padding: 5px;" cellspacing="0">
  <tr><td>
  <img src="https://groups.google.com/groups/img/3nb/groups_bar.gif"
         height="26" width="132" alt="Google Groups">
  </td></tr>
  <tr><td style="padding-left: 5px;font-size: 125%">
  <b>cmsfornerd</b>
  </td></tr>
  <tr><td style="padding-left: 5px">
  <a href="http://groups.google.com/group/cmsfornerd">Visit this group</a>
  </td></tr>
</table>

</div>

<h3>Get Updates</h3>

<br>



 
