<!-- For CmsForNerd Right side -->

<!-- Search Google -->
<center>
<form method="get" action="https://www.google.com/custom" target="google_window">
<table style="background-color: #ffffff;">
<tr><td nowrap="nowrap" valign="top" align="left" height="32">
<a href="https://www.google.com/">
<img src="https://www.google.com/logos/Logo_25wht.gif" border="0" alt="Google" style="vertical-align: middle;"></a>
<br>
<label for="sbi" style="display: none">Enter your search terms</label>
<input type="text" name="q" size="17" maxlength="255" value="" id="sbi">
</td></tr>
<tr><td valign="top" align="left">
<label for="sbb" style="display: none">Submit search form</label>
<input type="submit" name="sa" value="Search" id="sbb">
<input type="hidden" name="client" value="pub-9240760101409835">
<input type="hidden" name="forid" value="1">
<input type="hidden" name="channel" value="1583376637">
<input type="hidden" name="ie" value="ISO-8859-1">
<input type="hidden" name="oe" value="ISO-8859-1">
<input type="hidden" name="safe" value="active">
<input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;LH:50;LW:500;L:images/cmsfornerd.png;S:https://www.linuxmalaysia.com;FORID:1">
<input type="hidden" name="hl" value="en">
</td></tr></table>
</form>
</center>
<!-- Search Google -->

<br>

<script type="text/javascript"><!--
google_ad_client = "pub-9240760101409835";
//cmsfornerd 160x600, created 11/18/07
google_ad_slot = "3335197260";
google_ad_width = 160;
google_ad_height = 600;
//--></script>
<script type="text/javascript"
src="https://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

<a href="https://addons.mozilla.org/en-US/firefox/addon/html-validator/" target="_blank">
  <img src="images/tidy.png"
  alt="Validated by HTML Validator (based on Tidy)" style="height: 16px; width: 39px; border: 0;">
</a>
<br>

<!-- ROR BUTTON BEGIN -->
<a href="xml-sitemap.php"><img src="https://www.rorweb.com/rorinfo.gif" style="width: 80px; height: 15px; border: 0;" alt="ROR"></a><br><br>
<!-- ROR BUTTON END -->
