<h3>CmsForNerd Template</h3>
This is the template of <a
 href="https://www.linuxmalaysia.com"><span
 style="font-weight: bold;">CmsForNerd</span></a>
located in <span style="font-weight: bold;">contents</span>
directory (folder). You can use <a href="https://code.visualstudio.com/">VS Code</a>
to code your <span style="font-weight: bold;">HTML</span>.
Just copy the content between BODY TAG of your HTML source and put in
your INC file. Your INC file should be named as per the PHP file at the
top level of your website.<br>
<br>
For example if your page name is <span style="font-weight: bold;">search.php</span>
then the file in the <span style="font-weight: bold;">contents</span>
directory should be <span style="font-weight: bold;">search-body.inc</span>.
<br>
<br>
Don't forget to copy at the top level of your website the file <span
 style="font-weight: bold;">template.php</span> into
the&nbsp; name as per your file inside contents directory. Your
need to edit the PHP file to customize the information HTML TAG as per
your page content.<br>
