---
- name: Deploy PHP Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "/home/cmsfornerd/config/php/Dockerfile"
    owner: 1501
    group: 1501
    mode: '0600'

- name: Deploy PHP-FPM Configuration for Podman
  ansible.builtin.template:
    src: www.conf.j2
    dest: "/home/cmsfornerd/config/php/www.conf"
    owner: 1501
    group: 1501
    mode: '0600'

- name: Create Custom PHP-FPM Image with Extensions
  containers.podman.podman_image:
    name: localhost/cmsfornerd-php
    path: "/home/cmsfornerd/config/php"
    force: true
  become: true
  become_user: cmsfornerd

- name: Run PHP-FPM Container
  containers.podman.podman_container:
    name: cmsfornerd-php
    image: localhost/cmsfornerd-php
    state: started
    user: "1501:1501"
    restart_policy: always
    pod: cmsfornerd-pod
    volumes:
      - "/home/cmsfornerd/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:Z"
      - "/home/cmsfornerd/www:/var/www/html:Z"
      - "/home/cmsfornerd/logs/php:/var/log/php-fpm:Z"
    security_opt:
      - no-new-privileges
  become: true
  become_user: cmsfornerd
