---
- name: Deploy Nginx Configuration for Podman
  ansible.builtin.template:
    src: cmsfornerd.conf.j2
    dest: "/home/cmsfornerd/config/nginx/cmsfornerd.conf"
    owner: 1501
    group: 1501
    mode: '0600'

- name: Run Nginx Container
  containers.podman.podman_container:
    name: cmsfornerd-nginx
    image: docker.io/library/nginx:1.27
    state: started
    user: "1501:1501"
    restart_policy: always
    pod: cmsfornerd-pod
    volumes:
      - "/home/cmsfornerd/config/nginx/cmsfornerd.conf:/etc/nginx/conf.d/default.conf:Z"
      - "/home/cmsfornerd/www:/var/www/html:Z"
      - "/home/cmsfornerd/logs/nginx:/var/log/nginx:Z"
    security_opt:
      - no-new-privileges
  become: true
  become_user: cmsfornerd
